modLoader="javafml"
loaderVersion="[40,)"
#issueTrackerURL = ""
license = "LGPL-2.1"

[[mods]]
modId = "flowerybyg"
version = "${version}"
displayName = "FloweryBYG"
authors = "JustFoxx"
description = '''
FloweryBYG
'''
#logoFile = ""

[[dependencies.flowerybyg]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flowerybyg]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flowerybyg]]
    modId="flowerycore"
    mandatory=true
    versionRange="[3,)"
    ordering="NONE"
    side="BOTH"